export const SAVE_AUTH_DATA = "SAVE_AUTH_DATA";

export const SAVE_DASHBOARD_DATA = "SAVE_DASHBOARD_DATA";
export const SAVE_USERS_DATA = "SAVE_USERS_DATA";
export const SAVE_TIMEZONES_DATA = "SAVE_TIMEZONES_DATA";

export const RESET_STATE = "RESET_STATE";